# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ff3e088425eb50e96bd92562e081ced31998bcffb2f59102bc97845860aa6357f0202aa69f738037ba1483c3b137963bab60da7e9f5b01f7f5a5f1973e57bb4

test:
  secret_key_base: a3296ad7b86946fd7bdf8d0a5643894a99cf0376e8971eda7187ad3db4fc26f6b0ab7eacb61298b930bb1515c8af144a56920860233e2211a8cdf17fc7100ab0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
